DELIMITER //
CREATE EVENT IF NOT EXISTS delete_old_rentals
ON SCHEDULE EVERY 2 YEAR
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 10 YEAR
DO BEGIN
	DELETE FROM rental
    WHERE rental_end < now() - INTERVAL 2 year;
END //